'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TC001
    Public Property canumi As Integer
    Public Property cacod As String
    Public Property cadesc As String
    Public Property cadesc2 As String
    Public Property cacat As Nullable(Of Integer)
    Public Property caimg As String
    Public Property castc As Nullable(Of Boolean)
    Public Property caest As Nullable(Of Boolean)
    Public Property caserie As Nullable(Of Boolean)
    Public Property capcom As Nullable(Of Integer)
    Public Property cafing As Nullable(Of Date)
    Public Property cacemp As Nullable(Of Integer)
    Public Property cafact As Nullable(Of Date)
    Public Property cahact As String
    Public Property cauact As String

End Class
