'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TCA0011
    Public Property cabnumi As Integer
    Public Property cabtc1numi As Nullable(Of Integer)
    Public Property cabcant As Nullable(Of Decimal)
    Public Property cabpcom As Nullable(Of Decimal)
    Public Property cabputi As Nullable(Of Decimal)
    Public Property cabpven As Nullable(Of Decimal)
    Public Property cabnfr As String
    Public Property cabstocka As Nullable(Of Decimal)
    Public Property cabstockf As Nullable(Of Decimal)
    Public Property cabtca1numi As Nullable(Of Integer)

End Class
