'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TCA001
    Public Property caanumi As Integer
    Public Property caafdoc As Nullable(Of Date)
    Public Property caaprov As Nullable(Of Integer)
    Public Property caanfac As String
    Public Property caaobs As String
    Public Property caafact As Nullable(Of Date)
    Public Property caahact As String
    Public Property caauact As String

End Class
